spring:
  main:
    logging.level.org.zalando.logbook: TRACE
  sql.init.mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
